In [1]:
%pip install matplotlib seaborn

Requirement already satisfied: matplotlib in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (3.11.2)
Requirement already satisfied: seaborn in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in c:\users\ibnu syina\appdata\roaming\python\python313\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ibnu syina\appdata\roaming\python\python313\site-packages (from matplotlib) (3.0.0)
Requirement already satisfied: pandas>=1.2 in c:\users\ibnu syina\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.1.0)
Requirement already satisfied: tzdata in c:\users\ibnu syina\appdata\roaming\python\python313\site-packages (from pandas>=1.2->seaborn) (2026.5)
Requirement already satisfied: six>=1.6 in c:\users\ibnu syina\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# Jika library belum terpasang, jalankan di terminal:
# python -m pip install pandas numpy matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from IPython.display import display

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

print("Library berhasil diimpor.")

Library berhasil diimpor.

In [3]:
# Membaca dataset dari folder yang sama dengan notebook
file_path = Path("klasifikasimhs.csv")

if not file_path.exists():
    raise FileNotFoundError(
        f"File {file_path} tidak ditemukan. "
        "Pastikan CSV berada di folder yang sama dengan notebook."
    )

df = pd.read_csv(file_path)

print("Dataset berhasil dibaca.")
print(f"Jumlah baris  : {df.shape[0]}")
print(f"Jumlah kolom  : {df.shape[1]}")

display(df.head())

Dataset berhasil dibaca.
Jumlah baris  : 100
Jumlah kolom  : 6

,Tempat Tinggal,Pekerjaan Orang Tua,Penghasilan Orang Tua,Jumlah Tanggungan Orang Tua,Kendaraan,Kelayakan Keringanan UKT
0,0,PNS,10000000,3,1,0
1,0,TNI/POLRI,8000000,2,2,1
2,1,Petani,4000000,4,0,0
3,1,Nelayan,3000000,5,1,0
4,0,Buruh,2000000,2,1,1

In [4]:
# Informasi dasar dataset
print("=== INFORMASI DATASET ===")
df.info()

print("\n=== UKURAN DATASET ===")
print(f"Baris  : {df.shape[0]}")
print(f"Kolom  : {df.shape[1]}")

print("\n=== NAMA KOLOM ===")
print(df.columns.tolist())

print("\n=== TIPE DATA ===")
display(df.dtypes.rename("Tipe Data").to_frame())

print("\n=== STATISTIK DESKRIPTIF ===")
display(df.describe(include="all").T)

=== INFORMASI DATASET ===
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tempat Tinggal               100 non-null    int64
 1   Pekerjaan Orang Tua          100 non-null    str
 2   Penghasilan Orang Tua        100 non-null    int64
 3   Jumlah Tanggungan Orang Tua  100 non-null    int64
 4   Kendaraan                    100 non-null    int64
 5   Kelayakan Keringanan UKT     100 non-null    str
dtypes: int64(4), str(2)
memory usage: 4.8 KB

=== UKURAN DATASET ===
Baris  : 100
Kolom  : 6

=== NAMA KOLOM ===
['Tempat Tinggal', 'Pekerjaan Orang Tua', 'Penghasilan Orang Tua', 'Jumlah Tanggungan Orang Tua', 'Kendaraan', 'Kelayakan Keringanan UKT']

=== TIPE DATA ===

                            Tipe Data
Tempat Tinggal                  int64
Pekerjaan Orang Tua               str
Penghasilan Orang Tua           int64
Jumlah Tanggungan Orang Tua     int64
Kendaraan                       int64
Kelayakan Keringanan UKT          str

=== STATISTIK DESKRIPTIF ===

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Tempat Tinggal,100.0,NaN,NaN,NaN,0.5,0.502519,0.0,0.0,0.5,1.0,1.0
Pekerjaan Orang Tua,100,8,Ibu Rumah Tangga,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Penghasilan Orang Tua,100.0,NaN,NaN,NaN,5427000.0,2533128.181486,700000.0,3000000.0,5500000.0,8000000.0,10000000.0
Jumlah Tanggungan Orang Tua,100.0,NaN,NaN,NaN,2.59,1.129002,1.0,2.0,2.0,3.25,5.0
Kendaraan,100.0,NaN,NaN,NaN,1.07,0.655282,0.0,1.0,1.0,1.25,2.0
Kelayakan Keringanan UKT,100,3,1,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Ringkasan kualitas data sebelum cleaning
ringkasan_awal = pd.DataFrame({
    "Tipe Data": df.dtypes.astype(str),
    "Data Kosong": df.isna().sum(),
    "Persentase Kosong (%)": (
        df.isna().mean() * 100
    ).round(2),
    "Jumlah Nilai Unik": df.nunique(dropna=True)
})

display(ringkasan_awal)

print("Jumlah baris duplikat:", df.duplicated().sum())

print("\n=== BARIS DENGAN DATA KOSONG ===")
display(df[df.isna().any(axis=1)].head(10))

print("\n=== BARIS DUPLIKAT ===")
display(df[df.duplicated(keep=False)].head(10))

,Tipe Data,Data Kosong,Persentase Kosong (%),Jumlah Nilai Unik
Tempat Tinggal,int64,0,0.0,2
Pekerjaan Orang Tua,str,0,0.0,8
Penghasilan Orang Tua,int64,0,0.0,10
Jumlah Tanggungan Orang Tua,int64,0,0.0,5
Kendaraan,int64,0,0.0,3
Kelayakan Keringanan UKT,str,0,0.0,3

Jumlah baris duplikat: 77

=== BARIS DENGAN DATA KOSONG ===

Empty DataFrame
Columns: [Tempat Tinggal, Pekerjaan Orang Tua, Penghasilan Orang Tua, Jumlah Tanggungan Orang Tua, Kendaraan, Kelayakan Keringanan UKT]
Index: []

=== BARIS DUPLIKAT ===

,Tempat Tinggal,Pekerjaan Orang Tua,Penghasilan Orang Tua,Jumlah Tanggungan Orang Tua,Kendaraan,Kelayakan Keringanan UKT
1,0,TNI/POLRI,8000000,2,2,1
3,1,Nelayan,3000000,5,1,0
4,0,Buruh,2000000,2,1,1
6,0,PNS,9000000,2,2,1
7,1,Wiraswasta,6000000,1,1,1
8,1,Guru,7000000,2,1,1
9,0,Ibu Rumah Tangga,3000000,4,1,0
10,0,TNI/POLRI,8000000,2,2,1
11,1,Petani,4000000,3,0,0
13,0,Guru,7000000,2,1,1

In [6]:
# Membuat salinan agar data asli tetap aman
df_clean = df.copy()

# 1. Merapikan nama kolom
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

# 2. Merapikan spasi pada data teks
kolom_teks = df_clean.select_dtypes(
    include=["object", "string"]
).columns

for kolom in kolom_teks:
    df_clean[kolom] = df_clean[kolom].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

# 3. Menormalkan label target
kolom_target = "Kelayakan Keringanan UKT"

if kolom_target not in df_clean.columns:
    raise ValueError(f"Kolom target '{kolom_target}' tidak ditemukan.")

# Tampilkan label asli untuk diperiksa
print("Label target sebelum normalisasi:")
display(df_clean[kolom_target].value_counts(dropna=False).to_frame("Jumlah"))

# Asumsi: '1 1' merupakan salah ketik dari '1'.
# Verifikasi asumsi ini dengan sumber data sebelum digunakan.
df_clean[kolom_target] = df_clean[kolom_target].replace({
    "1 1": "1"
})

# 4. Konversi kolom numerik yang seharusnya berupa angka
kolom_numerik = [
    "Tempat Tinggal",
    "Penghasilan Orang Tua",
    "Jumlah Tanggungan Orang Tua",
    "Kendaraan"
]

for kolom in kolom_numerik:
    df_clean[kolom] = pd.to_numeric(
        df_clean[kolom], errors="coerce"
    )

# Konversi target menjadi angka setelah normalisasi
df_clean[kolom_target] = pd.to_numeric(
    df_clean[kolom_target], errors="coerce"
)

# 5. Menghapus baris yang label target-nya tidak valid/kosong.
# Label target tidak diisi menggunakan tebakan statistik.
jumlah_target_tidak_valid = df_clean[kolom_target].isna().sum()

df_clean = df_clean.dropna(subset=[kolom_target]).copy()

print("Baris dengan target tidak valid yang dihapus:",
      jumlah_target_tidak_valid)

# 6. Menghapus duplikat identik
duplikat_dihapus = df_clean.duplicated().sum()
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

print("Jumlah baris duplikat yang dihapus:", duplikat_dihapus)

# 7. Menangani nilai kosong pada kolom selain target
for kolom in df_clean.columns:
    if kolom == kolom_target:
        continue

    if df_clean[kolom].isna().any():
        if pd.api.types.is_numeric_dtype(df_clean[kolom]):
            # Median untuk kolom numerik
            df_clean[kolom] = df_clean[kolom].fillna(
                df_clean[kolom].median()
            )
        else:
            # Modus untuk kolom kategorikal
            modus = df_clean[kolom].mode(dropna=True)
            if not modus.empty:
                df_clean[kolom] = df_clean[kolom].fillna(
                    modus.iloc[0]
                )

# 8. Mengatur tipe data akhir
for kolom in kolom_numerik:
    df_clean[kolom] = df_clean[kolom].astype("int64")

# Target merupakan label kelas 0/1
df_clean[kolom_target] = df_clean[kolom_target].astype("int64")

print("Cleaning data selesai.")
print("Ukuran data setelah cleaning:", df_clean.shape)

display(df_clean.head())

Label target sebelum normalisasi:

                          Jumlah
Kelayakan Keringanan UKT
1                             64
0                             35
1 1                            1

Baris dengan target tidak valid yang dihapus: 0
Jumlah baris duplikat yang dihapus: 78
Cleaning data selesai.
Ukuran data setelah cleaning: (22, 6)

,Tempat Tinggal,Pekerjaan Orang Tua,Penghasilan Orang Tua,Jumlah Tanggungan Orang Tua,Kendaraan,Kelayakan Keringanan UKT
0,0,PNS,10000000,3,1,0
1,0,TNI/POLRI,8000000,2,2,1
2,1,Petani,4000000,4,0,0
3,1,Nelayan,3000000,5,1,0
4,0,Buruh,2000000,2,1,1

In [7]:
# Membandingkan kondisi sebelum dan sesudah cleaning
perbandingan = pd.DataFrame({
    "Sebelum Cleaning": [
        len(df),
        df.duplicated().sum(),
        int(df.isna().sum().sum()),
        df.shape[1]
    ],
    "Sesudah Cleaning": [
        len(df_clean),
        df_clean.duplicated().sum(),
        int(df_clean.isna().sum().sum()),
        df_clean.shape[1]
    ]
}, index=[
    "Jumlah Baris",
    "Jumlah Duplikat",
    "Total Data Kosong",
    "Jumlah Kolom"
])

display(perbandingan)

print("\n=== VALIDASI AKHIR ===")
print("Masih ada duplikat:", df_clean.duplicated().any())
print("Masih ada data kosong:", df_clean.isna().any().any())
print("Tipe data akhir:")
display(df_clean.dtypes.rename("Tipe Data").to_frame())

print("\nLabel target setelah cleaning:")
display(df_clean[kolom_target].value_counts().sort_index())

                   Sebelum Cleaning  Sesudah Cleaning
Jumlah Baris                    100                22
Jumlah Duplikat                  77                 0
Total Data Kosong                 0                 0
Jumlah Kolom                      6                 6

=== VALIDASI AKHIR ===
Masih ada duplikat: False
Masih ada data kosong: False
Tipe data akhir:

                            Tipe Data
Tempat Tinggal                  int64
Pekerjaan Orang Tua               str
Penghasilan Orang Tua           int64
Jumlah Tanggungan Orang Tua     int64
Kendaraan                       int64
Kelayakan Keringanan UKT        int64

Label target setelah cleaning:

Kelayakan Keringanan UKT
0    11
1    11
Name: count, dtype: int64

In [8]:
# Ringkasan setiap kolom
ringkasan_data = pd.DataFrame({
    "Tipe Data": df_clean.dtypes.astype(str),
    "Jumlah Data": df_clean.count(),
    "Nilai Unik": df_clean.nunique(),
    "Data Kosong": df_clean.isna().sum()
})

display(ringkasan_data)

# Ringkasan statistik kolom numerik
print("=== STATISTIK KOLOM NUMERIK ===")
display(df_clean.describe().T)

# Frekuensi pekerjaan orang tua
print("=== DISTRIBUSI PEKERJAAN ORANG TUA ===")
display(
    df_clean["Pekerjaan Orang Tua"]
    .value_counts()
    .rename_axis("Pekerjaan Orang Tua")
    .reset_index(name="Jumlah")
)

# Distribusi target
print("=== DISTRIBUSI KELAYAKAN UKT ===")
display(
    df_clean[kolom_target]
    .value_counts()
    .sort_index()
    .rename_axis("Kelayakan Keringanan UKT")
    .reset_index(name="Jumlah Mahasiswa")
)

                            Tipe Data  Jumlah Data  Nilai Unik  Data Kosong
Tempat Tinggal                  int64           22           2            0
Pekerjaan Orang Tua               str           22           8            0
Penghasilan Orang Tua           int64           22          10            0
Jumlah Tanggungan Orang Tua     int64           22           5            0
Kendaraan                       int64           22           3            0
Kelayakan Keringanan UKT        int64           22           2            0

=== STATISTIK KOLOM NUMERIK ===

,count,mean,std,min,25%,50%,75%,max
Tempat Tinggal,22.0,5.454545e-01,5.096472e-01,0.0,0.0,1.0,1.00,1.0
Penghasilan Orang Tua,22.0,5.077273e+06,2.746068e+06,700000.0,3000000.0,4500000.0,7000000.00,10000000.0
Jumlah Tanggungan Orang Tua,22.0,2.772727e+00,1.151885e+00,1.0,2.0,2.5,3.75,5.0
Kendaraan,22.0,9.545455e-01,6.529984e-01,0.0,1.0,1.0,1.00,2.0
Kelayakan Keringanan UKT,22.0,5.000000e-01,5.117663e-01,0.0,0.0,0.5,1.00,1.0

=== DISTRIBUSI PEKERJAAN ORANG TUA ===

  Pekerjaan Orang Tua  Jumlah
0              Petani       4
1    Ibu Rumah Tangga       4
2                 PNS       3
3               Buruh       3
4           TNI/POLRI       2
5             Nelayan       2
6          Wiraswasta       2
7                Guru       2

=== DISTRIBUSI KELAYAKAN UKT ===

   Kelayakan Keringanan UKT  Jumlah Mahasiswa
0                         0                11
1                         1                11

In [9]:
# Agregasi berdasarkan pekerjaan orang tua
agregasi_pekerjaan = (
    df_clean.groupby("Pekerjaan Orang Tua")
    .agg(
        Jumlah_Mahasiswa=(kolom_target, "size"),
        Rata_Rata_Penghasilan=("Penghasilan Orang Tua", "mean"),
        Rata_Rata_Tanggungan=("Jumlah Tanggungan Orang Tua", "mean"),
        Total_Penghasilan=("Penghasilan Orang Tua", "sum")
    )
    .round(2)
    .sort_values("Jumlah_Mahasiswa", ascending=False)
)

print("=== AGREGASI BERDASARKAN PEKERJAAN ORANG TUA ===")
display(agregasi_pekerjaan)

# Agregasi berdasarkan label kelayakan (menggunakan variabel kolom_target)
agregasi_ukt = (
    df_clean.groupby(kolom_target) 
    .agg(
        Jumlah_Mahasiswa=(kolom_target, "size"),
        Rata_Rata_Penghasilan=("Penghasilan Orang Tua", "mean"),
        Rata_Rata_Tanggungan=("Jumlah Tanggungan Orang Tua", "mean"),
        Total_Penghasilan=("Penghasilan Orang Tua", "sum")
    )
    .round(2)
    .sort_values("Jumlah_Mahasiswa", ascending=False)
)

print("\n=== AGREGASI BERDASARKAN LABEL KELAYAKAN ===")
display(agregasi_ukt)

=== AGREGASI BERDASARKAN PEKERJAAN ORANG TUA ===

,Jumlah_Mahasiswa,Rata_Rata_Penghasilan,Rata_Rata_Tanggungan,Total_Penghasilan
Pekerjaan Orang Tua,,,,
Ibu Rumah Tangga,4,4000000.00,3.50,16000000
Petani,4,3175000.00,3.50,12700000
PNS,3,9666666.67,2.33,29000000
Buruh,3,2000000.00,2.00,6000000
Nelayan,2,3000000.00,5.00,6000000
Guru,2,7000000.00,2.00,14000000
TNI/POLRI,2,8000000.00,2.00,16000000
Wiraswasta,2,6000000.00,1.00,12000000

=== AGREGASI BERDASARKAN LABEL KELAYAKAN ===

,Jumlah_Mahasiswa,Rata_Rata_Penghasilan,Rata_Rata_Tanggungan,Total_Penghasilan
Kelayakan Keringanan UKT,,,,
0,11,4063636.36,3.36,44700000
1,11,6090909.09,2.18,67000000

In [10]:
# Agregasi berdasarkan label kelayakan
agregasi_ukt = (
    df_clean.groupby(kolom_target)
    .agg(
        Jumlah_Mahasiswa=("Penghasilan Orang Tua", "size"),
        Rata_Rata_Penghasilan=("Penghasilan Orang Tua", "mean"),
        Rata_Rata_Tanggungan=("Jumlah Tanggungan Orang Tua", "mean"),
        Rata_Rata_Kendaraan=("Kendaraan", "mean")
    )
    .round(2)
)

print("=== AGREGASI BERDASARKAN KELAYAKAN UKT ===")
display(agregasi_ukt)

=== AGREGASI BERDASARKAN KELAYAKAN UKT ===

,Jumlah_Mahasiswa,Rata_Rata_Penghasilan,Rata_Rata_Tanggungan,Rata_Rata_Kendaraan
Kelayakan Keringanan UKT,,,,
0,11,4063636.36,3.36,0.64
1,11,6090909.09,2.18,1.27